INSERT INTO projects (title, description, image_url, tech_stack, status, demo_url, slug) VALUES ('College Projects', 'A curated collection of my academic projects, university assignments, and collaborative research work, demonstrating practical applications of software engineering and data science concepts.', '/assets/college-thumbnail.webp', ARRAY['Academic','University'], 'Completed', null, 'college-projects');
INSERT INTO projects (title, description, image_url, tech_stack, status, demo_url, slug) VALUES ('Vaultary', 'A Python-based cybersecurity utility engineered to rigorously analyze password strength, identify common vulnerabilities, and estimate brute-force cracking times to promote robust digital security habits.', '/assets/project-3.webp', ARRAY['Python','Flask','Zxcvbn'], 'Completed', 'https://vaultary.vercel.app', 'vaultary');
INSERT INTO projects (title, description, image_url, tech_stack, status, demo_url, slug) VALUES ('DevCollab Hub', 'A comprehensive full-stack MERN application designed to streamline developer collaboration. Features include real-time task tracking, secure user authentication, and an interactive Kanban board for agile project management.', '/assets/project-4.webp', ARRAY['MongoDB','Express.js','React','Node.js'], 'In Progress', null, 'devcollab-hub');
INSERT INTO certificates (title, date, issuer, description, category, pdf_url) VALUES ('MY Bharat Budget Quest 2026 – Final Round', 'April 12-13, 2026', 'Ministry of Youth Affairs & Sports', 'National Finalist in the MY Bharat Budget Quest 2026, selected from over 12 lakh participants for a virtual dialogue on public policy.', 'National Round', '/assets/my-bharat-budget-national-certificate.pdf');
INSERT INTO certificates (title, date, issuer, description, category, pdf_url) VALUES ('Certificate of Presentation - AIDE 2026', 'February 2026', 'IEEE & NMAMIT', 'Presented a machine learning research paper at the IEEE AIDE 2026 International Conference.', 'Paper Presentation', '/assets/aide-2026-certificate.pdf');
INSERT INTO certificates (title, date, issuer, description, category, pdf_url) VALUES ('AIC Nitte Internship', 'May 2025', 'Unknown', 'Completed a hands-on internship at AIC Nitte, focusing on tech innovation, startup processes, and entrepreneurship.', 'Tech Innovation', '/assets/AIC-certificate.pdf');
INSERT INTO blogs (title, excerpt, content, read_time_minutes, category, image_url, slug) VALUES ('How EVMs Work in India: Architecture & Security', 'An engineering breakdown of the Indian EVM system, exploring its distributed embedded architecture, strict state-machine flow, and security constraints.', 'Full blog content from markdown...', 5, 'Systems Engineering', '/assets/blog-9.webp', 'how-evms-work-in-india-architecture--security');
INSERT INTO blogs (title, excerpt, content, read_time_minutes, category, image_url, slug) VALUES ('Database Design Mistakes That Break Production Systems', 'Common database design mistakes that quietly break performance, scalability, and data integrity in real applications.', 'Full blog content from markdown...', 5, 'Backend Engineering', '/assets/blog-8.webp', 'database-design-mistakes-that-break-production-systems');
INSERT INTO blogs (title, excerpt, content, read_time_minutes, category, image_url, slug) VALUES ('Building Vaultary: Beyond "Password123"', 'Lessons from building Vaultary — exploring password entropy, real-world security challenges, and the engineering decisions behind a safer authentication system.', 'Full blog content from markdown...', 5, 'Cybersecurity', '/assets/blog-6.webp', 'building-vaultary-beyond-password123');
